name = "alsmaquinas"
compatibility_date = "2026-05-20"
pages_build_output_dir = "."

[vars]
FIREBASE_API_KEY = "AIzaSyAfBUa-AtmKZIDMlpw4N8_SlBRhy-1fh1Y"
FIREBASE_AUTH_DOMAIN = "catalogo-als.firebaseapp.com"
FIREBASE_PROJECT_ID = "catalogo-als"
FIREBASE_STORAGE_BUCKET = "catalogo-als.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID = "171009163821"
FIREBASE_APP_ID = "1:171009163821:web:ef28b7fc1232e60e5f2ea4"
FIREBASE_MEASUREMENT_ID = "G-Z0HH2XDHG5"
FIREBASE_ADMIN_UIDS = "dgn2kulnbrg1vTa8oFQYH3tbpZ52"
CLOUDINARY_CLOUD_NAME = "dooprpnho"
CLOUDINARY_API_KEY = "887389424183982"
CLOUDINARY_UPLOAD_PRESET = "als_admin_products"
CLOUDINARY_FOLDER = "als-maquinas/produtos"
